Collect small updates

diff --git a/bin/bin/chat-download b/bin/bin/chat-download
--- a/bin/bin/chat-download
+++ b/bin/bin/chat-download
@@ -14,6 +14,7 @@ if [[ $1 =~ $regex ]]; then
   id="${BASH_REMATCH[2]}"
 else
   echo "Could not identify video ID"
+  exit 1
 fi
 
 [ -n "$2" ] && chat_type=".$2"
@@ -31,6 +32,11 @@ title=$(echo "$html" | grep -oE "<title>.*</title>" | sed 's/<title>//' | sed 's
 channel=$(echo "$html" | grep -oE 'ownerChannelName":"[^"]*"' | sed 's/ownerChannelName":"//' | sed 's/"//')
 title=$(clean "$title")
 channel=$(clean "$channel")
+
+if [ -z "$channel" ]; then
+  echo "Unable to get channel name"
+  exit 1
+fi
 
 dir="${channel}"
 chat="${dir}/${title}-${id}${chat_type}.json"
diff --git a/bin/bin/stream-download b/bin/bin/stream-download
--- a/bin/bin/stream-download
+++ b/bin/bin/stream-download
@@ -14,6 +14,7 @@ if [[ $1 =~ $regex ]]; then
   id="${BASH_REMATCH[2]}"
 else
   echo "Could not identify video ID"
+  exit 1
 fi
 
 url="https://www.youtube.com/watch?v=${id}"
@@ -30,6 +31,11 @@ title=$(echo "$html" | grep -oE "<title>.*</title>" | sed 's/<title>//' | sed 's
 channel=$(echo "$html" | grep -oE 'ownerChannelName":"[^"]*"' | sed 's/ownerChannelName":"//' | sed 's/"//')
 title=$(clean "$title")
 channel=$(clean "$channel")
+
+if [ -z "$channel" ]; then
+  echo "Unable to get channel name"
+  exit 1
+fi
 
 dir="${channel}"
 file="${dir}/${title}-${id}.mp4"
